version: '2'
services:
  omnisocials-nginx:
    image: docker.quncrm.com/maiscrm/nginx:latest
    container_name: omnisocials-webserver
    volumes_from:
      - omnisocials-frontend
    volumes:
      - /var/log/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - omnisocials-backend
      - omnisocials-frontend
    extends:
      file: "docker-compose-common.yml"
      service: "common-dev"

  omnisocials-frontend:
    image: docker.quncrm.com/maiscrm/omnisocials-frontend:dev
    container_name: omnisocials-frontend
    volumes:
      - /srv/omnisocials-frontend
    volumes_from:
      - omnisocials-backend
    extends:
      file: "docker-compose-common.yml"
      service: "common-dev"

  omnisocials-backend:
    image: docker.quncrm.com/maiscrm/omnisocials-backend:dev
    container_name: omnisocials-backend
    volumes:
      - /srv/omnisocials-backend
    extends:
      file: "docker-compose-common.yml"
      service: "common-dev"

  omnisocials-worker:
    image: docker.quncrm.com/maiscrm/omnisocials-worker:dev
    container_name: omnisocials-worker
    volumes:
      - /var/log/omnisocials/worker:/var/log/supervisor
    extends:
      file: "docker-compose-common.yml"
      service: "common-dev"

  migration-once:
    image: docker.quncrm.com/maiscrm/omnisocials-backend:dev
    container_name: migration-once
    extends:
      file: "docker-compose-common.yml"
      service: "common-dev"
    restart: none
    command: /bin/bash -c "php src/yii migration/perform"
  
  
